### ISSUE TITLE
Channel registry exists bug

### ISSUE THREAD

**Issue by mfonda** [pyrus/Pyrus#35]
(Bug migrated from pearweb #17585)
## Description:

Create a new \PEAR2\Pyrus\Config with a directory that is not yet a registry. 
Get the channelregistry and check if 'pear2.php.net' exists.

This will return 1.

After this try to get the channel and a exception will be thrown.
## Test script:

```
$config = PEAR2\Pyrus\Config::singleton('D:\pear\testRepo');

// Expected result false or a exception saying that the channel registry is not initialized or initialize the registry.
// Current result 1
$res = $config->channelregistry->exists('pear2.php.net'); 
if ($res) {
    echo 'Channel exists ' . PHP_EOL;
} else {
    echo 'Unknow channel' . PHP_EOL;
}

// Throws 'PEAR2\Pyrus\ChannelFile\Exception: Invalid channel.xml'
// This is unexpected behavior
$config->channelregistry->get('pear2.php.net');
```
## Expected result:
- Make channelregistry->exists return false
  or
- Let it throw a exception
  or
- Let it initialize the repository
## Actual result:

See test script

**Comment by helgi** [comment]
I can not really reproduce this anymore. While it may be right that exists() returns a bool and get() throws an exception, I still can't create a test case for this.

I do not see what the problem is tho, it is pretty normal for exists() to be a boolean while if you attempt to fetch a resource that doesn't exist it would return an exception. Making exists() initialise wouldn't solve anything either and goes against the purpose of it.

I don't really think we should do anything here but I'm open for discussion on it.

**Comment by till** [comment]
I'm not uberfamiliar with the code, but I agree with Helgi's comment/statement.

`exists()` should not initialize this. The nature of these functions is to return a `boolean` and then it's up to the developer to handle that. Otherwise, it defeats the purpose of the function. Or it has to be renamed to `createIfNotExists()`, but that shouldn't return a `boolean` either.

**Comment by fpoirotte** [comment]
Then Matthew's first proposal still holds. The problem is, $config->channelregistry->exists('pear2.php.net'); returns true while any subsequent attempt to retrieve the channel with get() results in an exception being thrown.
For consistency, exists() should probably false while the registry hasn't been initialized, even for default channels.

Also, as a side note, the code in Pyrus\ChannelRegistry\Sqlite3 already does some initialization from its exists() method (it calls lazyInit() if the registry hasn't been initialized yet, which in turn calls _init() to do the actual initialization stuff).

**Comment by till** [comment]
I agree that `exists()` should not return `true` when it doesn't exist. 

It also should not initialize anything.

**Comment by till** [comment]
So, playing with this code, I noticed a few things:
- `exists()` sometimes returns `1` instead of `true`, I fixed this in a branch
- `exists()` seems to initialize the registry for default channels (`pear.php.net` and `pear2.php.net`)

The behavior is a little more than inconsistent.

**Comment by till** [comment]
Pushed my fix for the true or 1 issue to make the public API more consistent.

Otherwise, it seems like the default channels get initialized and there is no more exception. Whoever decided on that didn't read this ticket, or maybe just went ahead and did it anyway. I see no easy way to adjust that.
