### ISSUE TITLE
"unknown filesize" when downloading packages

### ISSUE THREAD

**Issue by cweiske** [pyrus/Pyrus#61]
Current git master shows "unknown filesize" when downloading packages:

```
$ ./scripts/pyrus install pecl/apc
Using PEAR installation found at /home/christian.weiske/php/phpfarm/inst/php-5.3.3/pear
Downloading pecl.php.net/APC
Unknown filesize.. 82 kb done..
```

Using 2.0.0a3 shows the full size.

**Comment by till** [comment]
Were you able to pin this down?

**Comment by till** [comment]
I tried to debug this.

It seems like the DownloadListener class is alright. It gets assigned (using observer pattern) to PEAR2\HTTP_Request. I'm guessing the bug is in there, but I couldn't figure it out.

**Comment by fpoirotte** [comment]
The issue lies in the cURL adapter in PEAR2\HTTP_Request, more precisely, in the progressCallback.
For some reason (I suspect, while the response headers haven't been processed yet), the callback function is called with all its parameters set to 0.
The callback method then does a great work at sending this $dltotal = 0 information to the DownloadListener through the observer pattern and ensures no more "filesize" notifications will be sent.
So, from the DownloadListener class, the total filesize is 0, which it happily translates into "Unknown filesize".

I'll try to come up with a patch unless someone beats me to it.

**Comment by till** [comment]
Closing this as it was fixed in said issue (in pear2/HTTP_Request).

**Comment by saltybeagle** [comment]
Just need to make sure we upgrade the bundled lib in the pyrus/vendor/ dir. `pyrus vendor upgrade PEAR2_HTTP_Request-0.3.0`
