### ISSUE TITLE
Issues with non-ascii characters

### ISSUE THREAD

**Issue by ghost** [pyrus/Pyrus#83]
When pyrus.phar is launched from a directory whose name contains non-ascii characters pyrus thows an XMLParser\Exception.

For example:

```
pierre@pierre-K52Jc:~$ php Téléchargements/pyrus.phar

PHP Warning:  XMLReader::setSchema(): Unable to set schema. This must be set prior to reading or schema contains    errors. in phar:///home/pierre/Téléchargements/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/XMLParser.php on line 171
PEAR2\Pyrus\XMLParser\Exception: Invalid XML document
PEAR2\Pyrus\XMLParser\Exception: Line 0: failed to load external entity "phar:///home/pierre/T%C3%A9l%C3%A9chargements/pyrus.phar/PEAR2_Pyrus-2.0.0a3/data/pear2.php.net/PEAR2_Pyrus/customcommand-2.0.xsd"

PEAR2\Pyrus\XMLParser\Exception: Line 0: Failed to locate the main schema resource at 'phar:///home/pierre/Téléchargements/pyrus.phar/PEAR2_Pyrus-2.0.0a3/data/pear2.php.net/PEAR2_Pyrus/customcommand-2.0.xsd'.
```

**Comment by fpoirotte** [comment]
I can reproduce this using the latest version of pyrus.phar as released on http://pear2.php.net/.
However, I cannot reproduce the results using a git clone for Pyrus / Pyrus_Developer... but I suspect the issue is specific to phar.

A similar issue [#69] has been discovered in alpha3 whereby libxml2 fails to load an XML schema when a phar archive or any other PHP stream is used and there are spaces in the path. I think you just found another way to trigger that issue.

**Comment by saltybeagle** [comment]
Confirmed that this is the same issue as #69 and has been fixed.
